.travis.yml
README.md

As discussed with @chris-allan, @jburel and @joshmoore, this PR adds support for Travis in `omero-marshal`. Merging this PR should ensure that for every subsequent change proposed to omero-marshal, the unit tests are automatically run by the Travis build for each of the supported lines of OMERO (currrently 5.1.x and 5.2.x) following the description of https://github.com/openmicroscopy/omero-marshal/pull/2.
The initial Travis build is defined as follows:
- uses a container based Travis
- installs the whitelisted `zeroc-ice34` package for convenience for the Ice dependencies (`libmcpp-dev`)
- downloads the custom OME Ice 3.5 build for Ubuntu 12.04 (also used in https://travis-ci.org/openmicroscopy/openmicroscopy) until the Travis infrastructure is migrating to Ubuntu 14.04
- downloads the …

Activate Travis for omero-marshal

---

omero_marshal/decode/__init__.py
tests/unit/conftest.py
tests/unit/test_shape_decoders.py

that would otherwise raise the following error: 
TypeError: 'NoneType' object has no attribute '__getitem__'

bugfix for non existing (optional) unit type attributes

---

MANIFEST.in
README.rst
setup.py

Pypi does not support rendering of Markdown readme files. Similarly to what has
been done for other pip distributed repositories (omego, yaclifw), this commit
converts the Readme from Markdown to reStructuredText which should be correctly
rendered by GitHub and Pypi.

Convert README from Markdown to reStructuredText

---

setup.py

With the release of 3.0.0b2 to Pypi it looks like python setup.py flake8 hangs. This should restore the Travis builds.

Cap flake8 version to be sub-3.0.0

---

omero_marshal/decode/__init__.py
tests/unit/test_base_decoder.py

When we moved to utilizing the field information in 0.4.0 to correctly
wrap properties using the relevant OMERO rtype an early null check was
inadvertently removed.  This null check was in `omero.rtypes.rtype()`
and partially hidden.  As we are directly using `omero.rtypes.rstring`
now where relevant, and its semantics are to handle `None` as
`RStringI('')`, all `None`'s were being decoded as `RString('')`.
This PR fixes that by adding a null check into `set_property()`.  As
all `None`'s are effectively handled the same and this style mimics the
previous `omero.rtypes.rtype()` semantics the sole test case on the
singular property should suffice.  It is not necessary to test every
string property for round-trip nullability.
Candidate for immediate 0.4.1 release.
/cc @knabar

Fix null strings

---

omero_marshal/decode/decoders/line.py
omero_marshal/decode/decoders/polyline.py
omero_marshal/encode/encoders/line.py
omero_marshal/encode/encoders/polyline.py
tests/unit/conftest.py
tests/unit/test_shape_decoders.py
tests/unit/test_shape_encoders.py

Marker attributes were added to `Line` and `Polyline` OMERO objects while aligning to the schema in 5.3 - see https://github.com/openmicroscopy/openmicroscopy/pull/4533.
This PR adds support for these markers in the shape encoders/decoders together with the corresponding unit tests.
/cc @will-moore @chris-allan

Add support for Line/Polyline markers

---

omero_marshal/encode/__init__.py
tests/unit/test_base_encoder.py

If details are unloaded, the object cannot currently be encoded. This PR fixes that.

Handle unloaded details

---

omero_marshal/encode/encoders/permissions.py
tests/unit/test_base_encoder.py
tests/unit/test_shape_encoders.py

Incredibly useful if you want to know the permission state of a given group and don't want to be parsing the `perm` string to find out.

Add convenience fields to encoded Permissions

---

omero_marshal/__init__.py
tests/unit/test_schema_version.py

As part of the multi-schema support in https://github.com/openmicroscopy/omero-marshal/pull/12, a top-level `get_schema_version()` method was added allowing to map the OMERO version to the Data Model version.
As reported by @mtbc, following the release of OMERO 5.3.0, the very strict version check for the latest schema in https://github.com/openmicroscopy/omero-marshal/blob/v0.5.0/omero_marshal/__init__.py#L57 breaks the usage of `omero-marshal` for any OMERO 5.3.x where x > 0.
This PR proposes to fix this bug by using a greater than check rather than a strict equality check so that any version greater than OMERO 5.3.0 and lower than OMERO 5.5.0 e.g. OMERO 5.3.1 or OMERO 5.4.0 for instance will be mapped to the 2016-06 data model schema.
A benefit of this conversative approach is we do …

OMERO version check: bug fix

---

.travis.yml

Following the release of omego 0.6.0, `omego download --ice 3.5` should be functional again for all OMERO 5.3.x artifacts.
Reverts the capping introduced in https://github.com/openmicroscopy/omero-marshal/commit/989ad906b6a2495a433f646e78cf74fb662b8de6
To test this PR, check Travis is green and that the 5.3 component is used the latest OMERO 5.3 release.
/cc @jburel @will-moore

Unpin the OMERO 5.3.0-m7 version and test with the latest OMERO 5.3

---

.travis.yml

Use trusty and bump ice version to 3.5 
No longer use pip to uninstall package installed using setup.py
* necessary to install ice via sudo see https://github.com/openmicroscopy/openmicroscopy/pull/5409 more details. This should be reverted when the issue is fixed
* no longer possible to uninstall omero-marshal using ``pip uninstall``. This is no longer the recommended  approach when installed via setup.py
* Change to ``bdist_egg`` since it is no longer created when running only ``bdist``

Use trusty

---

.travis.yml

Following https://www.openmicroscopy.org/2017/10/09/omero-5-4-0.html
To test this PR, check Travis is green. Review the matrix execution for OMERO 5.4 and verify that the OMERO 5.4.0 Python package is downloaded and used for running the unit tests.

Drop the specific milestone for OMERO

---

omero_marshal/__init__.py
tests/unit/test_schema_version.py

See https://github.com/openmicroscopy/openmicroscopy/pull/5913#issuecomment-440948870
This PR relaxes the checking of OMERO versions associated with the 2016-06 schema. It makes an assumption that any OMERO 5.3.0+ versions will be using the 2016-06 OME schema. On the other hand this should reduce the cost of releasing a patch version of `omero-marshal` every time we want to start an OMERO 5.x series.
/cc @joshmoore @jburel 
Proposed tag :`0.5.4`

5.5 and schema version check

---

.travis.yml

Travis is now switching to 3.6 as the default. Until Python 3 becomes supported this should ensure builds keep passing.

Encode Python version

---

README.rst
setup.py

All OME PyPI repos should now be pulled from the GitHub OME organization

Update links post organization transfer

---

omero_marshal/__init__.py
setup.py
tests/unit/test_schema_version.py

With the move of omero-web to PyPI, periodically development
versions prefixed with `dev`, `a`, `b`, or `rc` will be released.
See https://github.com/ome/openmicroscopy/pull/6100 for more information

Use major.minor for version detection

---

omero_marshal/__init__.py

This is needed to fix my omero-web unit tests with py3.

Fix encode/decode imports in __init__.py

---

omero_marshal/decode/__init__.py
omero_marshal/encode/__init__.py

This error may occur when omero_marshall is the first import
```
>>> import omero_marshal
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "omero_marshal/__init__.py", line 16, in <module>
from .encode import encoders
File "omero_marshal/encode/__init__.py", line 12, in <module>
from omero import RType
ImportError: cannot import name RType
```

import omero.all to avoid ordering errors

---

omero_marshal/__init__.py

replaces ``StrictVersion`` by ``Version`` to suppress DeprecationWarning
See https://github.com/pypa/packaging/issues/520 if we want to be stricter.

replace StrictVersion by Version

---

.github/workflows/tox.yml
tox.ini

Following https://github.com/ome/omero-py/blob/v5.19.0/CHANGELOG.md, this component can now be tested against Python 3.12

Add Python 3.12 to the testing matrix
